          <form class="form col-md-12 center-block" method="POST" action="#">
            <div class="form-group">
              <input type="email" name="email" class="form-control input-lg" placeholder="Email" required>
            </div>
            <div class="form-group">
              <input type="password" name="pass" class="form-control input-lg" placeholder="Senha" required>
            </div>
            <div class="form-group">
              <button class="btn btn-primary btn-lg btn-block" type="submit" name="logar">Entrar</button>
              <span class="pull-right"><a href="inicio/inscrevase">Inscreva-se</a></span><span><a href="#">Need help?</a></span>
              
            </div>
          </form>