
<!DOCTYPE html>
<html lang="en">

<head>
    <base href="/<?php echo MainConfig::$_dir;?>/<?php echo $this->dadosEvento["url"]?>/">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Area do usuario | <?php echo $_SESSION['event']['titulo']?></title>

    <!-- Bootstrap Core CSS -->
    <link href="../css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../css/simple-sidebar.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand" style="background:#fff">
                    <a href="#">
                        <img class="text-center" src="<?php echo $this->dadosEvento["logo"]?>">
                    </a>
                </li>
                <li>
                    <a href="user">Meu Perfil</a>
                </li>
                <!--<li>
                    <a href="user/palestras">Palestras</a>
                </li>
                <li>
                    <a href="user/minicursos">Minicurso</a>
                </li>
                <li>
                    <a href="user/programacao">Minha Programação</a>
                </li>
                <li>
                    <a href="user/subtrabalho">Submissão de Trabalhos</a>
                </li>
                <li>
                    <a href="user/maratona">Maratona</a>
                </li>-->
                <li>
                    <a href="user/alterar">Alterar Dados</a>
                </li>
                <li>
                    <a href="user/sair">Sair</a>
                </li>

            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <?php require_once("../app/Views/".$this->page);?>
                        <a onclick="#menu-toggle" class="btn btn-default" id="menu-toggle">Abrir Menu</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="http://code.jquery.com/jquery-2.1.3.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="../js/bootstrap.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

</body>

</html>
