<!DOCTYPE html>
<html lang="pt-br">
	<head>
		<base href="/<?php echo MainConfig::$_dir;?>/<?php echo $this->dadosEvento["url"]?>/">
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<title><?php echo $this->dadosEvento["nome"];?></title>
		<meta name="generator" content="Bootply" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<link href="../css/bootstrap.min.css" rel="stylesheet">
		<!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<link href="../css/styles.css" rel="stylesheet">
	</head>
	<body style="background:url('http://www.portal.ufv.br/crp/wp-content/uploads/2014/02/CRP.jpg') 50% fixed no-repeat; width:100%; height:100%;">
<!--login modal-->
<div id="loginModal" class="modal show" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <center><img class="text-center" src="<?php echo $this->dadosEvento["logo"]?>"></center>
          <h1 class="text-center" id="texto">Área do Congressista</h1>
      </div>
      <div class="modal-body">
          <?php require_once("../app/Views/".$this->page);?>
      </div>
      <center><small>Desenvolvido por</small><br><a href="http://www.infoalto.com.br"><img class="text-center" src="../img/logo.png" style="max-width:190px;height:50px"></a></center>
      

  </div>

  </div>
</div>
	<!-- script references -->
		<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
		<script src="../js/bootstrap.min.js"></script>
	</body>
</html>